### ISSUE TITLE
A question about the second "Text-knowledge guided quadratic term"

### ISSUE THREAD

**Issue by SydCS** [MaxZanella/MTA#1]
Great Paper! 
I have one small question though. How does the second term encourages samples with nearby text-based zero-shot predictions to have similar inlierness scores?
When $s_p$ and $s_q$ are alike, $w_{pq}$ is high. Then how are $y_p$ and $y_q$ to be similar?
Could you kindly give me some instructions? Thanks!

![image](https://github.com/user-attachments/assets/a8554e24-4553-4c32-8a12-589ccfaac2c4)

**Comment by MaxZanella** [comment]
Hello,

Thanks for the feedback, really appreciate it!
I suppose you meant "Then how does y_p and y_q are to be similar?".
I put the whole objective function to get the full picture:

![mta_objective](https://github.com/user-attachments/assets/d4f5abd7-c644-41df-8e11-a6c13b9c6183)

with

![mta_sp](https://github.com/user-attachments/assets/1157b505-e0ac-452b-8c83-c6d90bab5195)

As you mentioned, the idea is that when  s_p and s_q​ are alike, w_{p,q} is high​ (note that w_{p,q} is always positive). Considering the objective function, we have a minimization problem. Therefore, we want the second term you highlighted at the end of your question to be as large as possible (due to the negative sign). This term will be large if y_p*y_q is high (again each y_i is always positive), which corresponds to high inlierness scores for both augmented views p and q.

Hope this answered your question. If not, don't hesitate to ask for more clarification!

**Comment by SydCS** [comment]
Yes, it should be $y_p$ and $y_q$.
And that explains my question. $y_p$ and $y_q$ are both encouraged to be high. Thank you!
